# Generated by Django 3.2.4 on 2021-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210714_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
