# Generated by Django 3.2.4 on 2021-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='writer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
