# Generated by Django 3.2.4 on 2021-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_ctitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead0',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='ctitle',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
